### ISSUE TITLE
Type error in CurlClient.getCurlValue

### ISSUE THREAD

**Issue by a-gorbunov** [chobie/jira-api-restclient#103]
I tried to attach file to issue using this library and got an exception from `curl_file_create` which called in function `CurlClient.getCurlValue` . The reason is that
`function getCurlValue($file_string)` in **src/Jira/Api/Client/CurlClient.php** doesn't check type of input param.
`$file_string` param can be already `\CURLFile`, not `string`, than it doesn't need any transforms

Quick fix - add type check before transform:

```php
protected function getCurlValue($file_string)
{
	if ( !is_string($file_string) ) {
		return $file_string;
	}
	if ( !function_exists('curl_file_create') ) {
		return $file_string . '; filename=' . basename($file_string);
	}
	return curl_file_create(substr($file_string, 1), null, basename($file_string));
}
```

Sorry, have no time to create pull request.

**Comment by aik099** [comment]
I suggest instead of using `!is_string` use `!is_a(` function to check if that might be an object of a particular class. The `is_a` function is used instead of `instanceof` because in PPH versions where `CURLFile` class isn't available that would cause a Fatal Error.

**Comment by a-gorbunov** [comment]
`curl_file_create()` and `basename()` functions are expecting string as input param, so I don't think that `is_string()` is incorrect check. Anyway, I'll try to find free time so send PR

**Comment by aik099** [comment]
The `is_string` check is correct, but how it's used is not. With current check even if I give an array as input it will be returned as an array and that will result in an error.

**Comment by aik099** [comment]
The API for file upload is client agnostic and works with both `CurlClient` and `PHPClient` classes. You are allowed to specify only `/path/to/file` to upload a file. Behind the scenes the `CurlClient` will create `\CURLFile` instance itself (when one is needed).

Looks, that you're breaking that rule, when using library and specifically base your code on the fact, that `CurlClient` will always be used by default.

I suggest you using library as it expects to be used instead.
