### ISSUE TITLE
Integer overflow notice

### ISSUE THREAD

**Issue by rokasmi** [chobie/jira-api-restclient#109]
Got this notice while trying query issues:

`PHP Notice:  json_decode(): integer overflow detected in /var/www/vvs/releases/20160628161752/vendor/chobie/jira-api-restclient/src/Jira/Api.php on line 721`

**Comment by aik099** [comment]
Can you please:

* post code fragment, that can be used to reproduce the issue
* endpoint URL used
* any credentials (if that matter/possible)

**Comment by rokasmi** [comment]
Version: PHP 5.6.20-0+deb8u1 64bit. The whole system (+jira) is in the local network.
As i have figured out, the problem is with php. If passing higher int value than defined PHP_INT_MAX to json_decode() it throws integer overflow notice.

**Comment by jpastoor** [comment]
Does it work when you supply your large int as a string instead? Or is it somerhing returned by the jira api?
In that case please answer the other questions of @aik099

**Comment by aik099** [comment]
@rokasmi , that is really interesting. How come JIRA is passing a number larger than 64bit integer PHP can handle? If possible try debugging the request to JIRA and posting raw JSON (not decoded).

**Comment by aik099** [comment]
Doesn't matter. I'm guessing you have large number (64bit) encoded in JSON as integer and when decoded on 32bit PHP it ends up in notice you've mentioned.

Solution would be to use 64bit PHP, because you'll have same issues in MySQL.
