### ISSUE TITLE
Allow issue walker to be countable

### ISSUE THREAD

**Issue by gmask** [chobie/jira-api-restclient#117]
So far in all my projects I've used this package via Walker:

``` php
$jira = jiraApiClient();
$jiraIssues = new Walker($jira);

$jiraIssues->push('project = EXAMPLE');

foreach($jiraIssues as $issue) {
          $IssueSummary = $issue->getFields()['Summary'];
}
```

However using it this way I can't use any of the methods I see in the Result.php, like `getTotal()` etc. Ideally I'd like to be able to do something like `$jiraIssues->getTotal()` before processing the results in the foreach.

How can I use these methods? Is there some best practice to do what I'm trying to?

**Comment by aik099** [comment]
If I understand correctly, then what you're after is ability to find total number of issues available in the iterator (walker). Actually it is stored in `$this->total` protected property.

I can suggest PR with following changes:

1. make class implement `Countable` interface
2. add `count` method (from that interface) that would return `$this->total`

Then you can do `$issueCount = count($jiraIssues)` to get what you need.

**Comment by aik099** [comment]
@gmask , ping.

**Comment by gmask** [comment]
@aik099 I do not have the expertise to implement the changes you suggest.

**Comment by aik099** [comment]
That's not a problem. I'm just asking if proposed solution is what you're after. If that looks good to you, then we can implement it easily.

**Comment by gmask** [comment]
Yes I believe it is! Anything that can get me the number of results before iterating through them, e.g. `$jiraIssues->total()` or `count($jiraIssues)`.

Right now I am converting the object to an array so I can use `count()` on it, but this seems really bad to do.

**Comment by aik099** [comment]
PR created, ready for review. Sorry for the delay.

**Comment by gmask** [comment]
@aik099 Thanks!
