### ISSUE TITLE
Random "couldn't connect to host" errors on Travis

### ISSUE THREAD

**Issue by jpastoor** [chobie/jira-api-restclient#132]
Seems to happen sometimes?

https://travis-ci.org/chobie/jira-api-restclient/builds/153231673

**Comment by aik099** [comment]
Happened in other build for PHP 5.3 as well. Something tricky happens on internal PHP web server on Travis. Doesn't happen too often and is fixed by restarting particular build, so I guess not too critical for now.

**Comment by aik099** [comment]
Another occurrence on PHP 5.4: https://travis-ci.org/chobie/jira-api-restclient/jobs/153284095

**Comment by jpastoor** [comment]
Happens almost always now. Think we need to give it a bit of a priority to fix this since it obscures real problems.

**Comment by aik099** [comment]
It happens on random PHP version, but only when running several PHP versions in parallel. When I then restart build of individual version it always passes no matter how much times I restart it.

**Comment by jpastoor** [comment]
I also think you are the only one that can restart builds? Since I dont see that option (might not be looking in the right places though).

Hope the travis dudes come up with a solution.

**Comment by aik099** [comment]
We have identical permissions on the repo. Restart is done here: 
![2016-08-29_1620](https://cloud.githubusercontent.com/assets/1277526/18052710/9dd660bc-6e04-11e6-98a7-ad3e3293afea.png)

**Comment by aik099** [comment]
Guys from Travis CI team suggest to add following after Web Server is started:

```yml
before_script:
  - "~/.phpenv/versions/5.6/bin/php -S localhost:8000 -t $(pwd) > /dev/null 2> /tmp/webserver_output.txt &"
  - "export REPO_URL=http://localhost:8000/"
  - "while ! curl $REPO_URL >/dev/null 2>&1; do sleep 1; done"
```

They're suspecting, that tests start before Web Server startup is completed in background.

@jpastoor , can you please send a PR trying that.

**Comment by jpastoor** [comment]
Seems to work :) +1
