### ISSUE TITLE
Basic auth with password to be deprecated - start using API tokens

### ISSUE THREAD

**Issue by mansilladev** [chobie/jira-api-restclient#175]
See: https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-basic-auth-and-cookie-based-auth/

As of March 15, 2018, in accordance to the [Atlassian REST API Policy](https://developer.atlassian.com/platform/marketplace/atlassian-rest-api-policy/), support for passwords in HTTP basic auth requests will no longer be supported on or after September 15, 2018.

Instead of passwords, you should start using [API tokens](https://confluence.atlassian.com/cloud/api-tokens-938839638.html).

**Comment by aik099** [comment]
Luckily that won't require library code to be changed, because according to API Token usage example at https://confluence.atlassian.com/cloud/api-tokens-938839638.html the generated API token is used in place of regular password.

Have you tried that?

**Comment by mansilladev** [comment]
@aik099 - that’s right. You just need to substitute the password with an API token, and it will work just fine.

**Comment by aik099** [comment]
Good. Closing, because no changes to the code are needed.
