### ISSUE TITLE
Please implement option to specify the fields to return from JIRA in the search() method

### ISSUE THREAD

**Issue by SparklingSoftware** [chobie/jira-api-restclient#2]
Hi,

Again: Awesome library! :-)

As a... developer 

I would like to... be able to specify the fields that will be returned by JIRA 
while calling the search method with a JQL statement.

so that... I can reduce the amount of data send across the network and therefore increase the website responsiveness.

Cheers,
Stephan

**Comment by aik099** [comment]
Closing as the issue is now resolved.
