### ISSUE TITLE
How to use the function inside Api.php

### ISSUE THREAD

**Issue by vivekgs2007** [chobie/jira-api-restclient#30]
Hi,
I need to fetch the all the proejcts?

I am getting all projects in the object but unable to fetch the value. I used the $api->getProjects(), the result data in object format.

foreach ($api->getProjects() as $key => $value) {
	print_r($value);
}

**Comment by aik099** [comment]
@vivekgs2007 have you found the answer to your question?

**Comment by aik099** [comment]
Closing, because question seems to be answered. Feel free to reopen if that's not the case.
