### ISSUE TITLE
Is this library maintained?

### ISSUE THREAD

**Issue by aik099** [chobie/jira-api-restclient#54]

**Comment by gmask** [comment]
It certainly doesn't seem so with 22 pull requests, which is a shame since it's the best way to connect to JIRA in Laravel I've found. Hopefully Chobie returns or someone forks an updated version.

**Comment by jpastoor** [comment]
Does not seem so sadly :(

Took the time to take all open pull requests and merged them in a new fork:
https://github.com/jpastoor/jira-api-restclient

Feel free to use that one, and send additional pull requests also to me and I will merge them if OK.

ps. not trying to pirate anything from chobie, if he decides to return Ill try to get everything in my fork merged back in again.

**Comment by gmask** [comment]
@jpastoor thank you!

**Comment by aik099** [comment]
@jpastoor , as per my request in #59 @chobie added me & you as collaborators on this repo. This means we have merge/release rights. With great power comes great responsibility and therefore I'm asking you for every open issue/pull request express your opinion on whatever it does fit project vision and should be continued to be discussed (for issue) or be merged (for pull requests).

I then do the same and this way upon consensus we can process all stuff there is to process and hopefully make new release.
