### ISSUE TITLE
A problem with installing

### ISSUE THREAD

**Issue by rokasmi** [chobie/jira-api-restclient#81]
composer require chobie/jira-api-restclient 2.0.*

results in:
``- The requested package chobie/jira-api-restclient 2.0.* is satisfiable by chobie/jira-api-restclient[2.0.x-dev] but these conflict with your requirements or minimum-stability.``

I'm using symfony 2.8.4

**Comment by aik099** [comment]
Please use `2.0@dev` version constraint in `composer.json`. There is no release of 2.0 yet.

**Comment by aik099** [comment]
I've updated README.md with right composer installing command.

**Comment by jpastoor** [comment]
Nice :+1:
