### ISSUE TITLE
Remove dev dependency to PHPUnit

### ISSUE THREAD

**Issue by aik099** [chobie/jira-api-restclient#88]
There are 2 groups of people out there:

* one that thinks that PHPUnit is a must have dev Composer dependency
* one that thinks that PHPUnit must not be listed as dev Composer dependency

I belong to 2nd group and therefore recommend removing it from `composer.json`

**Comment by jpastoor** [comment]
Disagree, I think we should make it as easy as possible for people to develop on the project (i.e. require minimal outside setup). It's not like it is in the way of people who want to user their globally installed phpunit.

**Comment by aik099** [comment]
I'll leave it be then.
