### ISSUE TITLE
The "Api::getRoles" doesn't return any roles

### ISSUE THREAD

**Issue by PaulChanHK** [chobie/jira-api-restclient#98]
In Api.php:

	public function getRoles($project_key)
	{
		return $this->api(self::REQUEST_GET, sprintf('/rest/api/2/project/%s/roles', $project_key), array(), true);
	}
roles should be fixed as role,
i.e. return $this->api(self::REQUEST_GET, sprintf('/rest/api/2/project/%s/role', $project_key), array(), true);

**Comment by aik099** [comment]
Nice catch. Apparently this was never working since code was added in 1.0.0 version.

Would you mind sending a PR?

Docs Link: https://docs.atlassian.com/jira/REST/latest/#api/2/project/{projectIdOrKey}/role

**Comment by aik099** [comment]
PR created, ready for review. I haven't executed changed code and have changed it purely based on REST API docs.
